version: "3.8"

services:
  orchestrator:
    build:
      context: ./src/orchestrator
    ports:
      - "8000:8000"
    depends_on:
      - stt-service
    volumes:
      - stt-shared:/app/shared
      - ./keys/orchestrator-key.json:/app/key.json
    environment:
      - PREPROCESS_URL=http://audio-preprocessing-service:5003
      - STT_URL=http://stt-service:5001
      - PUBLIC_URL=http://localhost:8000
      # - STORAGE_DRIVER=gcs # Uncomment if using GCS
      - GCS_BUCKET=parlabot-audio
      - GOOGLE_APPLICATION_CREDENTIALS=/app/key.json


  audio-preprocessing-service:
    build:
      context: ./src/audio-preprocessing
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    volumes:
      - stt-shared:/app/shared
      - ./src/audio-preprocessing:/app
    environment:
      - PYTHONPATH=/app
    command: uvicorn main:app --host 0.0.0.0 --port 5003 --reload

  stt-service:
    build:
      context: ./src/stt-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - stt-shared:/app/shared
      - ./src/stt-service:/app
    environment:
      - PYTHONPATH=/app
    command: uvicorn main:app --host 0.0.0.0 --port 5001 --reload

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  phrase-service:
    build:
      context: ./src/phrase-service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017 
      - PYTHONPATH=/app
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    volumes:
      - ./src/phrase-service:/app
      - ./keys/parlabot-adcf69150750.json:/app/credentials.json:ro
      - stt-shared:/app/shared
    command: uvicorn app:app --host 0.0.0.0 --port 5002 --reload

  frontend-ui:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./src/frontend-ui:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"

volumes:
  stt-shared:
  mongo-data:
