// config.js
export const API_ORCHESTRATOR_URL = process.env.REACT_APP_API_ORCHESTRATOR_URL;
export const PHRASE_SERVICE_URL = process.env.REACT_APP_PHRASE_SERVICE_URL;
export const AUDIO_PREPROCESSING_URL = process.env.REACT_APP_AUDIO_PREPROCESSING_URL;
