name: Deploy UI

on:
  push:
    branches:
      - main
    paths:
      - 'src/frontend-ui/**'
      - 'infrastructure/ui/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: parlabot
        version: 'latest'

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Write .env.production to build context
      run: |
        echo "${{ secrets.UI_ENV_PROD }}" > src/frontend-ui/.env.production

    - name: Build and push container image
      run: |
        gcloud builds submit src/frontend-ui --tag us-central1-docker.pkg.dev/parlabot/parlabot-services/frontend-ui

    - name: Terraform init
      working-directory: infrastructure/ui
      run: terraform init

    - name: Terraform plan
      working-directory: infrastructure/ui
      run: terraform plan

    - name: Terraform apply
      working-directory: infrastructure/ui
      run: terraform apply -auto-approve
